name: nanoapi_build_and_deploy

on: [push]
jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      # Request build and stream output
      - name: Build Serverless functions and deploy via Nano API
        uses: Nano-API/Deploy@v0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}